platform:
  - x86
  - x64

branches:
  except:
    - gh-pages

environment:
  matrix:
    # NOTE: Currently only works on msvc toolchain due to required libs
    # Rust 1.3 required for $ty followed by ; in com_interface! macro
    # - RUST_VERSION: 1.3.0
    - RUST_VERSION: beta
    - RUST_VERSION: nightly

install:
  - ps: |
      if ($env:PLATFORM -eq "x86") {
        Start-FileDownload "https://static.rust-lang.org/dist/rust-$env:RUST_VERSION-i686-pc-windows-msvc.exe" -FileName rust.exe
      } else {
        Start-FileDownload "https://static.rust-lang.org/dist/rust-$env:RUST_VERSION-x86_64-pc-windows-msvc.exe" -FileName rust.exe
      }
  - rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
  - SET PATH=%PATH%;C:\Program Files\Rust\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  # Test default feature set
  - cargo test -v
  # Test each feature to ensure they work in isolation
  - cargo test -v --no-default-features --features="d3d11_2"
  - cargo test -v --no-default-features --features="d3d11_1"
  - cargo test -v --no-default-features --features="d3d11"
  - cargo test -v --no-default-features --features="dxgi1_4"
  - cargo test -v --no-default-features --features="dxgi1_3"
  - cargo test -v --no-default-features --features="dxgi1_2"
  - cargo test -v --no-default-features --features="dxgi"
  - cargo test -v --no-default-features --features="d2d"
  - cargo test -v --no-default-features --features="dwrite"
